=== Anish3866/Web/XML/Q15/Q15.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="userNameType">
    <xs:restriction base="xs:string">
      <xs:minLength value="8"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="postType">
    <xs:restriction base="xs:string">
      <xs:minLength value="5"/>
      <xs:maxLength value="8"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="passwordType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z].{7}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="genderType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="male"/>
      <xs:enumeration value="female"/>
      <xs:enumeration value="others"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="salaryType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="25000"/>
      <xs:maxInclusive value="50000"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="TU">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Employee" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Post" type="postType"/>
              <xs:element name="Salary" type="salaryType"/>
              <xs:element name="Gender" type="genderType"/>
              <xs:element name="UserName" type="userNameType"/>
              <xs:element name="Password" type="passwordType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Anish3866/Web/XML/Q15/Q15.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TU [
    <!ELEMENT TU (Employee+)>
    <!ELEMENT Employee (Post, Salary, Gender, UserName, Password)>
    <!ELEMENT Post (#PCDATA)>
    <!ELEMENT Salary (#PCDATA)>
    <!ELEMENT Gender (#PCDATA)>
    <!ELEMENT UserName (#PCDATA)>
    <!ELEMENT Password (#PCDATA)>
]>
<TU xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Q15.xsd">
    <Employee>
        <Post>Manager</Post>
        <Salary>45000</Salary>
        <Gender>male</Gender>
        <UserName>anish.gautam</UserName>
        <Password>P4ssword</Password>
    </Employee>
    <Employee>
        <Post>Lecturer</Post>
        <Salary>38000</Salary>
        <Gender>female</Gender>
        <UserName>aayush.gya</UserName>
        <Password>A1234567</Password>
    </Employee>
</TU>
