=== Anish3866/Web/XML/Q5/Q5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:simpleType name="emailType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="phoneType">
    <xs:restriction base="xs:string">
      <xs:pattern value="(98|97)[0-9]{8}"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="dobFormat">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first_name" type="xs:string"/>
                    <xs:element name="middle_name" type="xs:string" minOccurs="0"/>
                    <xs:element name="last_name" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="email" type="emailType"/>
              <xs:element name="phone" type="phoneType"/>
              <xs:element name="address" maxOccurs="2">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="type" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="permanent"/>
                            <xs:enumeration value="temporary"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="DOB">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="dobFormat">
                      <xs:attribute name="type" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="AD"/>
                            <xs:enumeration value="BS"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="rollno" type="xs:positiveInteger" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>


    <xs:unique name="uniqueRollNo">
      <xs:selector xpath="student"/>
      <xs:field xpath="@rollno"/>
    </xs:unique>
  </xs:element>

</xs:schema>

=== Anish3866/Web/XML/Q5/Q5.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Q5.xsd">
    <student rollno="08">
        <name>
            <first_name>Anish</first_name>
            <last_name>Gautam</last_name>
        </name>
        <email>anish206195@gmail.com</email>
        <phone>9841000000</phone>
        <address type="permanent">Baneshwor, Kathmandu</address>
        <address type="temporary">Kirtipur, Kathmandu</address>
        <DOB type="AD">2005-02-15</DOB>
    </student>
    
    <student rollno="03">
        <name>
            <first_name>Aayush</first_name>
            <middle_name>Bahadur</middle_name>
            <last_name>Gyawali</last_name>
        </name>
        <email>aayush.gyawali123@gmail.com</email>
        <phone>9745678901</phone>
        <address type="permanent">Butwal, Rupandehi</address>
        <DOB type="BS">2061-10-20</DOB>
    </student>
    
    <student rollno="21">
        <name>
          <first_name>Mavis</first_name>
          <last_name>Pahari</last_name>
        </name>
        <email>mavispahari123@gmail.com</email>
        <phone>9876543210</phone>
        <address type="permanent">Lalitpur, Nepal</address>
        <DOB type="AD">2004-12-05</DOB>
    </student>
</students>
