=== Anish3866/Web/XML/Q13/Q13.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="patientNumberType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{5}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="chargeType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="500"/>
      <xs:maxInclusive value="5000"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="patientType">
    <xs:sequence>
      <xs:element name="name">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="first" type="xs:string"/>
            <xs:element name="middle" type="xs:string" minOccurs="0"/>
            <xs:element name="last" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="patientNumber" type="patientNumberType"/>
      <xs:element name="doctorName" type="xs:string"/>
      <xs:element name="disease" type="xs:string" maxOccurs="unbounded"/>
      <xs:element name="consultationCharge" type="chargeType"/>
      <xs:element name="labTests">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="test" type="xs:string" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="hospital">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="patient" type="patientType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Anish3866/Web/XML/Q13/Q13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hospital [
    <!ELEMENT hospital (patient+)>
    <!ELEMENT patient (name, patientNumber, doctorName, disease+, consultationCharge, labTests)>
    <!ELEMENT name (first, middle?, last)>
    <!ELEMENT first (#PCDATA)>
    <!ELEMENT middle (#PCDATA)>
    <!ELEMENT last (#PCDATA)>
    <!ELEMENT patientNumber (#PCDATA)>
    <!ELEMENT doctorName (#PCDATA)>
    <!ELEMENT disease (#PCDATA)>
    <!ELEMENT consultationCharge (#PCDATA)>
    <!ELEMENT labTests (test+)>
    <!ELEMENT test (#PCDATA)>
]>
<hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Q13.xsd">
    <patient>
        <name>
            <first>Aayush</first>
            <middle>Bahadur</middle>
            <last>Gyawali</last>
        </name>
        <patientNumber>12345</patientNumber>
        <doctorName>Dr. Anish Gautam</doctorName>
        <disease>Fever</disease>
        <disease>Common Cold</disease>
        <consultationCharge>1500</consultationCharge>
        <labTests>
            <test>Blood Pressure Check</test>
            <test>Sugar Level Analysis</test>
            <test>Urine Test</test>
        </labTests>
    </patient>
</hospital>
