<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE booklist [
    <!ELEMENT booklist (book+)>
    <!ELEMENT book (title, author, publisher, edition, price)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT publisher (#PCDATA)>
    <!ELEMENT edition (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
]>
<?xml-stylesheet type="text/xsl" href="Q10.xsl"?>
<booklist>
    <book>
        <title>Web Programming</title>
        <author>Chrisbates</author>
        <publisher>Wiley</publisher>
        <edition>3</edition>
        <price>300</price>
    </book>
    <book>
        <title>Internet world-wide-web</title>
        <author>Ditel</author>
        <publisher>Pearson</publisher>
        <edition>3</edition>
        <price>400</price>
    </book>
    <book>
        <title>Computer Networks</title>
        <author>Foruouzan</author>
        <publisher>Mc Graw Hill</publisher>
        <edition>5</edition>
        <price>700</price>
    </book>
    <book>
        <title>DBMS Concepts</title>
        <author>Navath</author>
        <publisher>Oxford</publisher>
        <edition>5</edition>
        <price>600</price>
    </book>
    <book>
        <title>Linux Programming</title>
        <author>Subhitab Das</author>
        <publisher>Oxford</publisher>
        <edition>8</edition>
        <price>300</price>
    </book>
</booklist>
